AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  UsersApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'

  DevUsersFunction:
    Type: AWS::Serverless::Function
    Condition: IsDev
    Properties:
      CodeUri: src/
      Handler: lambda_handler_dev.lambda_handler
      Runtime: python3.9
      Events:
        GetUsersDev:
          Type: Api
          Properties:
            Path: /users
            Method: GET
            RestApiId: !Ref UsersApi

  ProdUsersFunction:
    Type: AWS::Serverless::Function
    Condition: IsProd
    Properties:
      CodeUri: src/
      Handler: lambda_handler_prod.lambda_handler
      Runtime: python3.9
      Events:
        GetUsersProd:
          Type: Api
          Properties:
            Path: /users
            Method: GET
            RestApiId: !Ref UsersApi

Conditions:
  IsDev: !Equals [!Ref Stage, dev]
  IsProd: !Equals [!Ref Stage, prod]
